import json
from io import StringIO

import data.lib.crypt as crypt


def load(fp: open):
    ans = fp.read().split('!!&#*DATA*#$&!!')[-1].split('!!&$#*K*#$&!!')
    ans = crypt.decrypt(ans[0], ans[1])
    return json.loads(ans)


def dump(obj: dict, fp: open):
    try:
        key = fp.read().split('!!&#*DATA*#$&!!')[1].split('!!&$#*K*#$&!!')[1]
    except IndexError:
        key = crypt.generate_salt()
    obj = crypt.encrypt(f'{_format(obj)}', key)
    fp.write(f'!!WARNING!! This file is NOT Json! This file is generated by jsoncrypt. EDITING THIS FILE CAN CORRUPT HIMSELF!\n!!&#*DATA*#$&!!{obj}!!&$#*K*#$&!!{key}')


def _format(obj):
    ans = StringIO()
    json.dump(obj, ans)
    ans.seek(0)
    return ans.read()